user:
  name:
    min_size: 2
    max_size: 30
    is_presence: true
  email:
    format:
    max_size: 255
    is_unique: true
    is_presence: true
  password:
    min_size: 6
    max_size: 255
    is_presence: true
    is_allow_blank: true
  avatar:
    is_presence: true
    is_allow_blank: true
    max_size_in_MB: 2
    unit: MB
    accepted_format: image/jpeg,image/gif,image/png
    store_dir: "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
    extension_white_list:
      - jpg
      - jpeg
      - gif
      - png
    profile_avatar_size: "150x150"
    list_user_avatar_size: "50x50"
    image_size_edit: 200
  gravatar:
    image_size: 40
per_page: 10
status:
  inactive: 0
  active: 1
  finish: 2
  finished: 1
format_date: "%Y/%m/%d"
user_course:
  true: t
  false: f
course_subjects:
  status:
    unstart: 0  
    start: 1
    finish: 2
activities:
  supervisor_update_course: 1
  admin_update_subject: 2
  supervisor_start_subject: 3
  supervisor_finish_subject: 4
  trainee_finish_task: 5
  supervisor_assign_trainee: 6
  supervisor_remove_trainee: 7
  number_activites_show: 10
